FROM php:7.3.6-fpm-alpine3.9

RUN apk add --no-cache shadow openssl \
    bash \
    mysql-client \
    nodejs \
    npm \
    git \
    freetype-dev \
    libjpeg-turbo-dev \
    libpng-dev
RUN docker-php-ext-install pdo pdo_mysql
RUN docker-php-ext-configure gd \
    --with-gd \
    --with-freetype-dir=/usr/include/ \
    --with-png-dir=/usr/include/ \
    --with-jpeg-dir=/usr/include/ && \
  NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) && \
  docker-php-ext-install -j${NPROC} gd 

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www

RUN rm -rf /var/www/html && ln -s public html

COPY . /var/www

RUN chmod -R 777 backend/storage

EXPOSE 9000
