name: ci-docker-compose
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Decrypt credentials
        run: gcloud kms decrypt --ciphertext-file=./backend/storage/credentials/google/service-account-storage.json.enc --plaintext-file=./backend/storage/credentials/google/service-account-storage.json --location=global --keyring=code-videos --key=service-account
      - name: Build de containers
        run: docker-compose -f docker-compose.prod.yaml down -v && docker-compose -f docker-compose.prod.yaml up -d --build --force-recreate
      - name: Copy .env
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker exec micro-videos-app cp backend/.env.example backend/.env
      - name: Copy .env testing
        run: docker exec micro-videos-app cp backend/.env.testing.example backend/.env.testing
      - name: Run composer install
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker exec micro-videos-app composer install -d backend/
      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: "10s"
      - name: Test containers
        run: docker-compose ps
      - name: Run clean cache
        run: docker exec micro-videos-app php backend/artisan cache:clear
      - name: Run migrations
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker exec micro-videos-app php backend/artisan migrate
      - name: Run Tests
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker exec micro-videos-app ./backend/vendor/bin/phpunit -c backend/phpunit.xml
