name: ci-docker-compose
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build de containers
        run: docker-compose up -d
      - name: Run Tests
        run: docker-compose exec app ./vendor/bin/phpunit
