name: ci-docker-compose
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build de containers
        run: docker-compose up -d --build
      - name: Run Tests
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker exec micro-videos-app ls
