name: ci-docker-compose
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          registry: docker.pkg.github.com
          compose_file: docker-compose.prod.yaml
        # run: docker-compose -f docker-compose.prod.yaml up -d --build
      - uses: actions/checkout@v2
      - name: Copy .env
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker exec micro-videos-app cp .env.example .env
      - name: Copy .env testing
        run: docker exec micro-videos-app cp .env.testing.example .env.testing
      - name: Run composer install
        run: docker exec micro-videos-app composer install
      - name: Run migrations
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker exec micro-videos-app php artisan migrate
      - name: Run clean cache
        run: docker exec micro-videos-app php artisan cache:clear
      - name: Run Tests
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker exec micro-videos-app ./vendor/bin/phpunit